version: '3.8'

services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/python:0-3-bullseye
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    init: true
    command: sleep infinity

  nginx:
    image: nginx
